"""Added teh rejection_reason column in kyc_docs table

Revision ID: 044a6e4d63d6
Revises: 65e7409abcab
Create Date: 2025-09-02 23:34:45.220049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044a6e4d63d6'
down_revision: Union[str, Sequence[str], None] = '65e7409abcab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_docs', sa.Column('rejection_reason', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyc_docs', 'rejection_reason')
    # ### end Alembic commands ###
