"""added is_blocked field to guide table

Revision ID: 1faacad64e55
Revises: ad291b697dde
Create Date: 2025-09-17 06:10:06.048805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1faacad64e55'
down_revision: Union[str, Sequence[str], None] = 'ad291b697dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guide', sa.Column('is_blocked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guide', 'is_blocked')
    # ### end Alembic commands ###
