"""add expertise column to guides table

Revision ID: 27c65fbd1566
Revises: 54302b80c146
Create Date: 2025-09-15 20:06:41.102921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c65fbd1566'
down_revision: Union[str, Sequence[str], None] = '54302b80c146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guide', sa.Column('expertise', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guide', 'expertise')
    # ### end Alembic commands ###
