"""remove dob field from guide and host

Revision ID: 4a633300c024
Revises: 6d47e31cc6cb
Create Date: 2025-09-21 01:34:18.329541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a633300c024'
down_revision: Union[str, Sequence[str], None] = '6d47e31cc6cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guide', 'dob')
    op.drop_column('host', 'dob')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('dob', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('guide', sa.Column('dob', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
