"""create guide and languages table

Revision ID: 54302b80c146
Revises: 044a6e4d63d6
Create Date: 2025-09-15 19:35:27.427070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '54302b80c146'
down_revision: Union[str, Sequence[str], None] = '044a6e4d63d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guide',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.String(length=255), nullable=False),
    sa.Column('profession', sa.String(length=255), nullable=False),
    sa.Column('hourly_rate', sa.String(length=255), nullable=False),
    sa.Column('house_name', sa.String(length=255), nullable=False),
    sa.Column('landmark', sa.String(length=255), nullable=True),
    sa.Column('pincode', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['guide.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('languages')
    op.drop_table('guide')
    # ### end Alembic commands ###
