"""made dob field nullable

Revision ID: 6d47e31cc6cb
Revises: 69d5b0313c90
Create Date: 2025-09-20 13:51:02.121681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d47e31cc6cb'
down_revision: Union[str, Sequence[str], None] = '69d5b0313c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
