"""added price_per_night and bedrooms to property model

Revision ID: 7b29d8532701
Revises: 4b85839ecc4a
Create Date: 2025-09-30 01:12:18.657995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b29d8532701'
down_revision: Union[str, Sequence[str], None] = '4b85839ecc4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('max_guests', sa.Integer(), nullable=False))
    op.add_column('property', sa.Column('bedrooms', sa.Integer(), nullable=False))
    op.add_column('property', sa.Column('price_per_night', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'price_per_night')
    op.drop_column('property', 'bedrooms')
    op.drop_column('property', 'max_guests')
    # ### end Alembic commands ###
