"""Change the guide_id to user_id in languages

Revision ID: 8f7883ce21ec
Revises: 27c65fbd1566
Create Date: 2025-09-16 20:12:59.241906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7883ce21ec'
down_revision: Union[str, Sequence[str], None] = '27c65fbd1566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_user_language', 'languages', ['user_id', 'language'])
    op.drop_constraint(op.f('languages_guide_id_fkey'), 'languages', type_='foreignkey')
    op.create_foreign_key(None, 'languages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('languages', 'guide_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('guide_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'languages', type_='foreignkey')
    op.create_foreign_key(op.f('languages_guide_id_fkey'), 'languages', 'guide', ['guide_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_user_language', 'languages', type_='unique')
    op.drop_column('languages', 'user_id')
    # ### end Alembic commands ###
