"""made field changes in host table

Revision ID: ad291b697dde
Revises: c20b312a0220
Create Date: 2025-09-17 03:50:05.792008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad291b697dde'
down_revision: Union[str, Sequence[str], None] = 'c20b312a0220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('property_type', sa.String(length=255), nullable=False))
    op.add_column('property_address', sa.Column('house_name', sa.String(length=255), nullable=False))
    op.drop_column('property_address', 'building')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_address', sa.Column('building', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('property_address', 'house_name')
    op.drop_column('property', 'property_type')
    # ### end Alembic commands ###
