"""Add child_friendly column

Revision ID: c928ac67559e
Revises: 919288574c8a
Create Date: 2025-10-08 16:48:20.928624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c928ac67559e'
down_revision: Union[str, Sequence[str], None] = '919288574c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('child_friendly', sa.Boolean(), nullable=True))
    op.execute("UPDATE property SET child_friendly = False")

    op.alter_column('property', 'child_friendly', nullable=False, server_default='False')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'child_friendly')
    # ### end Alembic commands ###
